name: App release

on:
  pull_request_target:
    types:
      - closed
    branches: ['main']

jobs:
  if_merged:
    if: ${{ github.event.pull_request.merged }}

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: 'v'
          release_name: 'Release <RELEASE_VERSION>'
          max_commits: 20
